### ISSUE TITLE
楼主，程序启动后，必须固定在chrome的右上角吗？有的中文汉化不全？

### ISSUE THREAD

**Issue by HeliusHao** [xiaoluoboding/chrome-web-bookmark#2]
![image](https://user-images.githubusercontent.com/33107305/182521005-a6660a53-2813-4ee5-8bcd-c19a4ac17a6f.png)
![image](https://user-images.githubusercontent.com/33107305/182521080-921942b1-0639-453b-8478-d26608032795.png)
可能还有其它地方有中文不全的哦

**Comment by iamsee** [comment]
@HeliusHao  其实是左上角啦，顺便说一句作者这编码频率真牛逼

**Comment by xiaoluoboding** [comment]
> ![image](https://user-images.githubusercontent.com/33107305/182521005-a6660a53-2813-4ee5-8bcd-c19a4ac17a6f.png) ![image](https://user-images.githubusercontent.com/33107305/182521080-921942b1-0639-453b-8478-d26608032795.png) 可能还有其它地方有中文不全的哦

可以可以，都找到这里来了，确实 One Tab Group 插件还未开源，开源后可以有固定的反馈渠道

1、固定在 chrome 左上角，是“固定”功能，固定的标签会自动排序为 NO1，所以原谅我为了方便让用户找到 One Tab Group，其实可以自己“取消固定”
2、国际化问题下个版本一定翻译全了😂

**Comment by HeliusHao** [comment]
谢谢，我现在正在试用这个软件，希望这个软件越来越好



---原始邮件---
发件人: "Yunwei ***@***.***&gt;
发送时间: 2022年8月3日(周三) 晚上6:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [one-tab-group/chrome-web-bookmark] 楼主，程序启动后，必须固定在chrome的右上角吗？有的中文汉化不全？ (Issue #2)




  
  可能还有其它地方有中文不全的哦
  
可以可以，都找到这里来了，确实 One Tab Group 插件还未开源，开源后可以有固定的反馈渠道
 
1、固定在 chrome 左上角，是“固定”功能，固定的标签会自动排序为 NO1，所以原谅我为了方便让用户找到 One Tab Group，其实可以自己“取消固定”
 2、国际化问题下个版本一定翻译全了😂
