### ISSUE TITLE
one-tab-group 建议

### ISSUE THREAD

**Issue by aloasut** [xiaoluoboding/chrome-web-bookmark#3]
1.建议标签页、分组页双击空白处切换折叠/展开，因为这个操作会非常频繁。

2.建议标签页、分组页功能按钮隐藏。现在如果内容多了，整个屏幕都是这些按钮。

3.建议增加同步功能，例如webdav、网盘等。可以是付费功能。

4.希望对标 Cluster Tab Manager，这个插件很多好评，可惜作者消失了几年了。很多人追着付费。

**Comment by xiaoluoboding** [comment]
@aloasut 🙏 感谢建议，下个版本会解决 1、2，3 也是未来的一个规划，4 我正在学习😂
